flowable:
  process-definition-location-prefix: classpath*:/flowable/**/
  enable-history-cleaning: true
  history-cleaning-after: 1d
  process:
    async:
      executor:
        # After redeployment job might not be picked up for this time (execution will be locked without executor):
        async-job-lock-time: PT10M # !!!! Keeping lock is done by Heartbeat
        max-async-jobs-due-per-acquisition: 512 # Prevent immediate acquisition of next chunk by setting large value

flowable-executor:
  pool:
    core-pool-size: 10
    max-pool-size: 10
    queue-capacity: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deeplearning4j-trainer?currentSchema=deeplearning4j_trainer
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: deeplearning4j_trainer
      maximum-pool-size: 5
  jpa:
    database-platform: com.valb3r.deeplearning4j_trainer.config.PostgreSQL10DialectWithBlob
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: false # Do not use Spring Multipart mechanism in order to store uploads directly to S3 (otherwise they will be stored in a temp file of disk)
  flyway:
    baseline-on-migrate: true
  data:
    rest:
      base-path: /api
  session:
    store-type: jdbc

server:
  port: 8080
  forward-headers-strategy: framework

directories:
  input: file:///Users/valentynberezin/IdeaProjects/acoustico/input/
  output: file:///Users/valentynberezin/IdeaProjects/acoustico/output/

s3:
  access-key-id: minio
  secret-key: minio-123456
  region: eu-central-1
  is-http: true

access:
  users:
    - username: admin
      password: admin
      roles: USER