flowable:
  process-definition-location-prefix: classpath*:/flowable/**/
  enable-history-cleaning: true
  history-cleaning-after: 1d
  process:
    async:
      executor:
        # After redeployment job might not be picked up for this time (execution will be locked without executor):
        async-job-lock-time: PT120M # !!!! Any step should not take longer than (async-job-lock-time) 120 minutes, otherwise lock will expire and job can be picked by other exec
        max-async-jobs-due-per-acquisition: 1 # Long running jobs may get stuck in queue (we do not want them there)

flowable-executor:
  pool:
    core-pool-size: 1
    max-pool-size: 1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deeplearning4j-trainer?currentSchema=deeplearning4j_trainer
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: deeplearning4j_trainer
  jpa:
    database-platform: com.valb3r.deeplearning4j_trainer.config.PostgreSQL10DialectWithBlob
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: false # Do not use Spring Multipart mechanism in order to store uploads directly to S3 (otherwise they will be stored in a temp file of disk)
  flyway:
    baseline-on-migrate: true
  data:
    rest:
      base-path: /api
  session:
    store-type: jdbc

server:
  forward-headers-strategy: framework

directories:
  input: s3://localhost:9000/training-bucket/input/
  output: s3://localhost:9000/training-bucket/output/

s3:
  access-key-id: minio
  secret-key: minio-123456
  region: eu-central-1
  is-http: true

access:
  users:
    - username: admin
      password: admin
      roles: USER