flowable:
  process-definition-location-prefix: classpath*:/flowable/**/
  enable-history-cleaning: true
  history-cleaning-after: 1d
  process:
    async:
      executor:
        async-job-lock-time: PT10M
        max-async-jobs-due-per-acquisition: 1 # Long running jobs may get stuck in queue (we do not want them there)

flowable-executor:
  pool:
    core-pool-size: 1
    max-pool-size: 1
    queue-capacity: 1 # Long running jobs should not be placed on queue as jobs on queue are affected by `async-job-lock-time`

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deeplearning4j-trainer?currentSchema=deeplearning4j_trainer
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: deeplearning4j_trainer
  jpa:
    database-platform: com.valb3r.deeplearning4j_trainer.config.PostgreSQL10DialectWithBlob
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  flyway:
    baseline-on-migrate: true
  data:
    rest:
      base-path: /api
  session:
    store-type: jdbc

server:
  forward-headers-strategy: framework

directories:
  input: s3://localhost:9000/training-bucket/input/
  output: s3://localhost:9000/training-bucket/output/

s3:
  access-key-id: minio
  secret-key: minio-123456
  region: eu-central-1
  is-http: true

access:
  users:
    - username: admin
      password: admin
      roles: USER