flowable:
  process-definition-location-prefix: classpath*:/flowable/**/
  enable-history-cleaning: true
  history-cleaning-after: 1d

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deeplearning4j-trainer?currentSchema=deeplearning4j_trainer
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: deeplearning4j_trainer
  jpa:
    database-platform: com.valb3r.deeplearning4j_trainer.config.PostgreSQL10DialectWithBlob
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  flyway:
    baseline-on-migrate: true
  data:
    rest:
      base-path: /api

server:
  forward-headers-strategy: framework

directories:
  input: file:///tmp/trainer/input
  output: file:///tmp/trainer/output

access:
  users:
    - username: admin
      password: admin
      roles: USER