flowable:
  process-definition-location-prefix: classpath*:/flowable/**/
  enable-history-cleaning: true
  history-cleaning-after: 1d

spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:./deeplearning4j_trainer.db
    username: sa
    password: a8u239joomlss12ea
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  flyway:
    baseline-on-migrate: true
  data:
    rest:
      base-path: /api

server:
  forward-headers-strategy: framework

directories:
  input: ./input
  output: ./output

access:
  users:
    - username: admin
      password: admin
      roles: USER