# Builds pushes and merges on develop branch
name: Master branch build, test, deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v2
        name: Cache gradle dependencies
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set short git commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(./gradlew printCommitSha | grep COMMIT | cut -d":" -f2)"

      - name: Build project backend and run tests
        run: ./gradlew clean test --stacktrace

      - name: Build project docker images (UI and Backend)
        run: ./gradlew buildImage

      - name: Push To Github container registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: valb3r/deeplearning4j_trainer-trainer:latest
          tags: latest
          registry: https://ghcr.io/valb3r
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
